# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'SunSeeker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON', git: 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', branch: 'swift3'
  # Pods for SunSeeker

  target 'SunSeekerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
